In [4]:
import pandas as pd 
import seaborn as sns 
import matplotlib.pyplot as plt

# Getting data from yahoo finance

In [5]:
import yfinance as yf

In [8]:
# download the data 
df = yf.download("AAPL", start = "2011-01-01", end = "2023-10-31", progress = False)
df.sample(10)

,Open,High,Low,Close,Adj Close,Volume
Date,,,,,,
2014-08-22,25.072500,25.367500,25.047501,25.330000,22.605776,176736000
2014-05-14,21.158215,21.335714,21.133572,21.209642,18.834871,166404000
2022-03-31,177.839996,178.029999,174.399994,174.610001,173.085175,103049300
2022-04-08,171.779999,171.779999,169.199997,170.089996,168.604645,76575500
2016-10-13,29.197500,29.360001,28.930000,29.245001,27.113466,140769600
2021-04-19,133.509995,135.470001,133.339996,134.839996,132.872726,94264200
2012-01-04,14.642857,14.810000,14.617143,14.765714,12.533087,260022000
2021-01-19,127.779999,128.710007,126.940002,127.830002,125.777061,90757300
2016-12-12,28.322500,28.750000,28.122499,28.325001,26.395353,105497600
2014-03-12,19.089643,19.191071,19.000000,19.164642,16.924320,199326400

In [ ]:
# Microsoft
msft = yf.Ticker("MSFT")

# get all stock info
msft.info

In [18]:
# get historical market data
hist = msft.history(period="1mo")
hist

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2023-10-03 00:00:00-04:00,320.829987,321.390015,311.209991,313.390015,21033500,0.0,0.0
2023-10-04 00:00:00-04:00,314.029999,320.040009,314.000000,318.959991,20720100,0.0,0.0
2023-10-05 00:00:00-04:00,319.089996,319.980011,314.899994,319.359985,16965600,0.0,0.0
2023-10-06 00:00:00-04:00,316.549988,329.190002,316.299988,327.260010,25645500,0.0,0.0
2023-10-09 00:00:00-04:00,324.750000,330.299988,323.179993,329.820007,19891200,0.0,0.0
2023-10-10 00:00:00-04:00,330.959991,331.100006,327.670013,328.390015,20557100,0.0,0.0
2023-10-11 00:00:00-04:00,331.209991,332.820007,329.140015,332.420013,20063200,0.0,0.0
2023-10-12 00:00:00-04:00,330.570007,333.630005,328.720001,331.160004,19313100,0.0,0.0
2023-10-13 00:00:00-04:00,332.380005,333.829987,326.359985,327.730011,21072400,0.0,0.0
2023-10-16 00:00:00-04:00,331.049988,336.140015,330.600006,332.640015,22158000,0.0,0.0
2023-10-17 00:00:00-04:00,329.589996,333.459991,327.410004,332.059998,18338500,0.0,0.0
2023-10-18 00:00:00-04:00,332.489990,335.589996,328.299988,330.109985,23153600,0.0,0.0
2023-10-19 00:00:00-04:00,332.149994,336.880005,330.910004,331.320007,25052100,0.0,0.0
2023-10-20 00:00:00-04:00,331.720001,331.920013,325.450012,326.670013,25012600,0.0,0.0
2023-10-23 00:00:00-04:00,325.470001,332.730011,324.390015,329.320007,24374700,0.0,0.0
2023-10-24 00:00:00-04:00,331.299988,331.839996,327.600006,330.529999,31153600,0.0,0.0
2023-10-25 00:00:00-04:00,345.019989,346.200012,337.619995,340.670013,55053800,0.0,0.0
2023-10-26 00:00:00-04:00,340.540009,341.630005,326.940002,327.890015,37828500,0.0,0.0
2023-10-27 00:00:00-04:00,330.429993,336.720001,328.399994,329.809998,29856500,0.0,0.0
2023-10-30 00:00:00-04:00,333.410004,339.450012,331.829987,337.309998,22828100,0.0,0.0
2023-10-31 00:00:00-04:00,338.850006,339.000000,334.690002,338.109985,20265300,0.0,0.0
2023-11-01 00:00:00-04:00,339.790009,347.420013,339.649994,346.070007,28158800,0.0,0.0
2023-11-02 00:00:00-04:00,347.239990,348.829987,344.769989,348.320007,24299600,0.0,0.0
2023-11-03 00:00:00-04:00,349.630005,353.167999,347.329987,353.167999,11042560,0.0,0.0

In [14]:
# show actions (dividends, splits, capital gains)
msft.actions
msft.dividends
msft.splits
msft.capital_gains  # only for mutual funds & etfs

[]

In [19]:
# show holders
msft.major_holders
msft.institutional_holders
msft.mutualfund_holders

,Holder,Shares,Date Reported,% Out,Value
0,Vanguard Total Stock Market Index Fund,231883087,2023-06-29,0.0312,81875598339
1,Vanguard 500 Index Fund,177034936,2023-06-29,0.0238,62509264903
2,Fidelity 500 Index Fund,85181943,2023-08-30,0.0115,30076891941
3,SPDR S&P 500 ETF Trust,83514381,2023-09-29,0.0112,29488092481
4,iShares Core S&P 500 ETF,70264910,2023-09-29,0.0095,24809836814
5,Vanguard Growth Index Fund,63262454,2023-06-29,0.0085,22337339651
6,"Invesco ETF Tr-Invesco QQQ Tr, Series 1 ETF",58757680,2023-08-30,0.0079,20746749016
7,Vanguard Institutional Index Fund-Institutiona...,50756950,2023-06-29,0.0068,17921771289
8,Growth Fund Of America Inc,39310503,2023-09-29,0.0053,13880145360
9,Vanguard Information Technology Index Fund,39119308,2023-08-30,0.0053,13812636318

In [20]:
# show options expirations
msft.options

('2023-11-03',
 '2023-11-10',
 '2023-11-17',
 '2023-11-24',
 '2023-12-01',
 '2023-12-08',
 '2023-12-15',
 '2024-01-19',
 '2024-02-16',
 '2024-03-15',
 '2024-04-19',
 '2024-05-17',
 '2024-06-21',
 '2024-09-20',
 '2024-12-20',
 '2025-01-17',
 '2025-06-20',
 '2025-12-19',
 '2026-01-16')

In [21]:
# show news
msft.news

[{'uuid': '8c645ac0-562a-3197-9c73-09e97e32af41',
  'title': 'Dow Jones Rallies On Weak Jobs Report; Apple Stock Slides On Earnings',
  'publisher': "Investor's Business Daily",
  'link': 'https://finance.yahoo.com/m/8c645ac0-562a-3197-9c73-09e97e32af41/dow-jones-rallies-on-weak.html',
  'providerPublishTime': 1699020650,
  'type': 'STORY',
  'thumbnail': {'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/yFYixt4zfmpEGBBg4OOySw--~B/aD01NjM7dz0xMDAwO2FwcGlkPXl0YWNoeW9u/https://media.zenfs.com/en/ibd.com/c17b5b65818a93054b26ab66c9c27269',
     'width': 1000,
     'height': 563,
     'tag': 'original'},
    {'url': 'https://s.yimg.com/uu/api/res/1.2/1T1bZIustlZy3R5TX9lYzg--~B/Zmk9ZmlsbDtoPTE0MDtweW9mZj0wO3c9MTQwO2FwcGlkPXl0YWNoeW9u/https://media.zenfs.com/en/ibd.com/c17b5b65818a93054b26ab66c9c27269',
     'width': 140,
     'height': 140,
     'tag': '140x140'}]},
  'relatedTickers': ['^DJI',
   'AAPL',
   'TW',
   'UNH',
   'NVDA',
   'MELI',
   'AMZN',
   'MSFT']},
 {'uuid': '7fdc106e-9117-37e3-9c3f-8b901a11da78',
  'title': 'Why This 1 Computer and Technology Stock Could Be a Great Addition to Your Portfolio',
  'publisher': 'Zacks',
  'link': 'https://finance.yahoo.com/news/why-1-computer-technology-stock-133007369.html',
  'providerPublishTime': 1699018207,
  'type': 'STORY',
  'thumbnail': {'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/eeFsK50..hTdRBoBNDEyoA--~B/aD03MTE7dz05MDA7YXBwaWQ9eXRhY2h5b24-/https://media.zenfs.com/en/zacks.com/d2f7ed3d1940141716bfd200f5c94c6b',
     'width': 900,
     'height': 711,
     'tag': 'original'},
    {'url': 'https://s.yimg.com/uu/api/res/1.2/U.GeD2pq81ETtKFpwtAvMA--~B/Zmk9ZmlsbDtoPTE0MDtweW9mZj0wO3c9MTQwO2FwcGlkPXl0YWNoeW9u/https://media.zenfs.com/en/zacks.com/d2f7ed3d1940141716bfd200f5c94c6b',
     'width': 140,
     'height': 140,
     'tag': '140x140'}]},
  'relatedTickers': ['MSFT']},
 {'uuid': 'a9f41512-f1f2-3633-8753-34e3be153b6b',
  'title': "Here's Why We Think Microsoft (NASDAQ:MSFT) Is Well Worth Watching",
  'publisher': 'Simply Wall St.',
  'link': 'https://finance.yahoo.com/news/heres-why-think-microsoft-nasdaq-120247052.html',
  'providerPublishTime': 1699012967,
  'type': 'STORY',
  'thumbnail': {'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/eFZZVJx6QdqQsl5Qimg4Rw--~B/aD00MzI7dz0xMTk0O2FwcGlkPXl0YWNoeW9u/https://media.zenfs.com/en/simply_wall_st__316/a5d5a89dd6ab73bc7694c99b9023ec2d',
     'width': 1194,
     'height': 432,
     'tag': 'original'},
    {'url': 'https://s.yimg.com/uu/api/res/1.2/5Fy.yFFq_J2cr_4EvCbCFw--~B/Zmk9ZmlsbDtoPTE0MDtweW9mZj0wO3c9MTQwO2FwcGlkPXl0YWNoeW9u/https://media.zenfs.com/en/simply_wall_st__316/a5d5a89dd6ab73bc7694c99b9023ec2d',
     'width': 140,
     'height': 140,
     'tag': '140x140'}]},
  'relatedTickers': ['MSFT']},
 {'uuid': '0cd49481-26a1-38f6-aa7f-f22d20bed9be',
  'title': '3 Things About Microsoft the Smartest Investors Know',
  'publisher': 'Motley Fool',
  'link': 'https://finance.yahoo.com/m/0cd49481-26a1-38f6-aa7f-f22d20bed9be/3-things-about-microsoft-the.html',
  'providerPublishTime': 1699011300,
  'type': 'STORY',
  'thumbnail': {'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/Nwamg.3p_Y5vKrZqlLhp6w--~B/aD01MzIzO3c9NzU0MzthcHBpZD15dGFjaHlvbg--/https://media.zenfs.com/en/motleyfool.com/372e9612c8bbc69543d452ad089fb3d2',
     'width': 7543,
     'height': 5323,
     'tag': 'original'},
    {'url': 'https://s.yimg.com/uu/api/res/1.2/dOzzCYFe0wROYoDgejV2Ow--~B/Zmk9ZmlsbDtoPTE0MDtweW9mZj0wO3c9MTQwO2FwcGlkPXl0YWNoeW9u/https://media.zenfs.com/en/motleyfool.com/372e9612c8bbc69543d452ad089fb3d2',
     'width': 140,
     'height': 140,
     'tag': '140x140'}]},
  'relatedTickers': ['MSFT']},
 {'uuid': '3c4d91cc-b137-3708-ad9f-42b954beef28',
  'title': '2 Artificial Intelligence (AI) Stocks That Could Go Parabolic',
  'publisher': 'Motley Fool',
  'link': 'https://finance.yahoo.com/m/3c4d91cc-b137-3708-ad9f-42b954beef28/2-artificial-intelligence.html',
  'providerPublishTime': 1699009860,
  'type': 'STORY',
  'thumbnail': {'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/osdAXnjKMt2Wnra6UKlfhQ--~B/aD0yMDI3O3c9MzEwMDthcHBpZD15dGFjaHlvbg--/https://media.zenfs.com/en/motleyfool.com/84253db5bec4f55a164cd490d92475af',
     'width': 3100,
     'height': 2027,
     'tag': 'original'},
    {'url': 'https://s.yimg.com/uu/api/res/1.2/BGysJhI7VSoNYNMLyzR1wQ--~B/Zmk9ZmlsbDtoPTE0MDtweW9mZj0wO3c9MTQwO2FwcGlkPXl0YWNoeW9u/https://media.zenfs.com/en/motleyfool.com/84253db5bec4f55a164cd490d92475af',
     'width': 140,
     'height': 140,
     'tag': '140x140'}]},
  'relatedTickers': ['NVDA', 'MSFT']},
 {'uuid': '46e1e9d1-3577-325b-9c59-16c932f715f9',
  'title': '1 Green Flag and 1 Red Flag for Microsoft Stock',
  'publisher': 'Motley Fool',
  'link': 'https://finance.yahoo.com/m/46e1e9d1-3577-325b-9c59-16c932f715f9/1-green-flag-and-1-red-flag.html',
  'providerPublishTime': 1699007100,
  'type': 'STORY',
  'thumbnail': {'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/RGLELfyOiv1JxSclRC9czg--~B/aD0xNDE0O3c9MjEyMDthcHBpZD15dGFjaHlvbg--/https://media.zenfs.com/en/motleyfool.com/a198d4ca0d0a05648302aa1880b3c33d',
     'width': 2120,
     'height': 1414,
     'tag': 'original'},
    {'url': 'https://s.yimg.com/uu/api/res/1.2/1HUOvV5KMe6KjiKAR3w8vw--~B/Zmk9ZmlsbDtoPTE0MDtweW9mZj0wO3c9MTQwO2FwcGlkPXl0YWNoeW9u/https://media.zenfs.com/en/motleyfool.com/a198d4ca0d0a05648302aa1880b3c33d',
     'width': 140,
     'height': 140,
     'tag': '140x140'}]},
  'relatedTickers': ['MSFT']},
 {'uuid': '81b5ab43-7f1a-3154-919e-b575c5eb7482',
  'title': 'Palantir Is Quietly Emerging as a Leader in Artificial Intelligence (AI)',
  'publisher': 'Motley Fool',
  'link': 'https://finance.yahoo.com/m/81b5ab43-7f1a-3154-919e-b575c5eb7482/palantir-is-quietly-emerging.html',
  'providerPublishTime': 1699005900,
  'type': 'STORY',
  'thumbnail': {'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/venctvlfghNBVqLH9zVk3g--~B/aD0zMTExO3c9NTUzMDthcHBpZD15dGFjaHlvbg--/https://media.zenfs.com/en/motleyfool.com/d68f3c77d501aa4325219c42f7223496',
     'width': 5530,
     'height': 3111,
     'tag': 'original'},
    {'url': 'https://s.yimg.com/uu/api/res/1.2/XIXY6eiYlaEWSobt2K7AWg--~B/Zmk9ZmlsbDtoPTE0MDtweW9mZj0wO3c9MTQwO2FwcGlkPXl0YWNoeW9u/https://media.zenfs.com/en/motleyfool.com/d68f3c77d501aa4325219c42f7223496',
     'width': 140,
     'height': 140,
     'tag': '140x140'}]},
  'relatedTickers': ['PLTR', 'MSFT', 'GOOG']},
 {'uuid': 'd99c0350-c80b-3d44-9e7b-84523a2c41ac',
  'title': 'Is Microsoft Stock a Buy?',
  'publisher': 'Motley Fool',
  'link': 'https://finance.yahoo.com/m/d99c0350-c80b-3d44-9e7b-84523a2c41ac/is-microsoft-stock-a-buy%3F.html',
  'providerPublishTime': 1699005780,
  'type': 'STORY',
  'thumbnail': {'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/3A2KVmL3pfZOOOSa1KI2eg--~B/aD0xNDE0O3c9MjEyMDthcHBpZD15dGFjaHlvbg--/https://media.zenfs.com/en/motleyfool.com/c3de78db3fbaa69556d45aa071d932f6',
     'width': 2120,
     'height': 1414,
     'tag': 'original'},
    {'url': 'https://s.yimg.com/uu/api/res/1.2/.H__LgolXieezUmAhsvFYw--~B/Zmk9ZmlsbDtoPTE0MDtweW9mZj0wO3c9MTQwO2FwcGlkPXl0YWNoeW9u/https://media.zenfs.com/en/motleyfool.com/c3de78db3fbaa69556d45aa071d932f6',
     'width': 140,
     'height': 140,
     'tag': '140x140'}]},
  'relatedTickers': ['MSFT', 'ADBE']}]